# Generated by Django 5.1.2 on 2024-11-05 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('keywords', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=255)),
                ('smtp_server', models.CharField(max_length=100)),
                ('smtp_email', models.CharField(max_length=100)),
                ('smtp_password', models.CharField(max_length=100)),
                ('smtp_port', models.CharField(max_length=5)),
                ('youtue', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('facebook', models.CharField(max_length=100)),
                ('icon', models.ImageField(blank=True, upload_to='images/')),
                ('aboutus', models.CharField(max_length=255)),
                ('contact', models.CharField(max_length=255)),
            ],
        ),
    ]
