# Generated by Django 5.1.2 on 2024-11-09 13:46

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='aboutus',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='settings',
            name='contact',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
        migrations.AlterField(
            model_name='settings',
            name='email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='facebook',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='instagram',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtp_email',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtp_password',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtp_port',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AlterField(
            model_name='settings',
            name='smtp_server',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='settings',
            name='youtue',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
