# Generated by Django 5.1.1 on 2024-11-23 14:59

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='student',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
